version: '3'
services:
  api:
    container_name: 'nodejs-home-service-api'
#   image: hallovarvara/nodejs-home-service-api
    platform: linux/arm64
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    networks:
      - bridgeapidb
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: 'nodejs-home-service-db'
    image: hallovarvara/nodejs-home-service-db
    platform: linux/arm64
    build:
      dockerfile: database/Dockerfile
      context: .
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT_INNER}
    networks:
      - bridgeapidb
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

networks:
  bridgeapidb:
    driver: bridge
    ipam:
      config:
        - subnet: ${BRIDGE_SUBNET_IP}

volumes:
  postgres: